version: '3.4'
services:
  workplace:
    container_name: ${PROJECT_PREFIX}-workplace
    entrypoint: DreamDaemon paradise.dmb -port ${INNER_PORT} -trusted -close -verbose
    build:
      context: ../../
      args:
        - BYOND_MAJOR=${BYOND_MAJOR}
        - BYOND_MINOR=${BYOND_MINOR}
        - RUSTG=${RUSTG}
        - NODEJS=${NODEJS}
        - DREAM_MAKER_COMMAND=./tools/ci/dm.sh paradise.dme -M${MAP}
    restart: always
    ports:
      - ${OUTER_PORT}:${INNER_PORT}
    volumes:
      - ${STORAGE_PATH}/config:/station/config
      - ${STORAGE_PATH}/data:/station/data
  db:
    container_name: ${PROJECT_PREFIX}-db
    image: mariadb:10.7.1-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: feedback
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${STORAGE_PATH}/mariadb:/var/lib/mysql
      - ${DB_MIGRATION_PATH}/paradise_schema.sql:/docker-entrypoint-initdb.d/migrate1.sql
      - ${DB_MIGRATION_PATH}/paradise_schema_prefixed.sql:/docker-entrypoint-initdb.d/migrate2.sql
