name: CI
on:
  push:
    branches:
    - master220
  pull_request:
    branches:
    - master220

env:
  BYOND_MAJOR: "514"
  BYOND_MINOR: "1575"
  SPACEMAN_DMM_VERSION: suite-1.7.2

jobs:
  run_linters:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Tools
        run: |
          bash tools/ci/install_build_deps.sh
          bash tools/ci/install_dreamchecker.sh
      - name: Run Linters
        run: |
          find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/ci/json_verifier.py
          tools/ci/build_tgui.sh
          tools/ci/check_grep.sh
          python3 tools/ci/check_line_endings.py
          ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1
      - name: Annotate Lints
        uses: yogstation13/DreamAnnotate@v1
        if: always()
        with:
          outputFile: output-annotations.txt
