name: 'Merge Conflict Detection'
on:
  pull_request:
    branches: [master220, whitelist220]
  push:
    branches: [master220, whitelist220]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'invalid'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
